version: "3"


services:
  library:
    image: "library-spring-boot-image"
    build:
      context: .
      dockerfile: "Dockerfile"
    restart: on-failure
    ports:
      - 8080:8080
    depends_on:
      - chumakdb
    environment:
      MYSQL_HOST: chumakdb
      MYSQL_DATABASE: library
      MYSQL_PASSWORD: Nastusia_1503
      MYSQL_ROOT_PASSWORD: Nastusia_1503

    command: sh -c './wait-for chumakdb:3306 -- npm start'
  chumakdb:
    image: mysql
    restart: on-failure
    volumes:
      - /var/lib/docker/volumes/mysql-db:/var/lib/mysql-db
    ports:
      - 3307:3306
    environment:
      MYSQL_HOST: chumakdb
      MYSQL_DATABASE: library
      MYSQL_PASSWORD: Nastusia_1503
      MYSQL_ROOT_PASSWORD: Nastusia_1503
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./env/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    env_file:
      - ./env/grafana.env

  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: 
      - --path.procfs=/host/proc 
      - --path.sysfs=/host/sys
      - --collector.filesystem.ignored-mount-points
      - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)
    ports:
      - 9100:9100 
